apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_SHARED_PRELOAD_LIBRARIES
          value: "pg_stat_statements"
        - name: POSTGRES_MAX_CONNECTIONS
          value: "100"
        - name: POSTGRES_SHARED_BUFFERS
          value: "128MB"
        - name: POSTGRES_EFFECTIVE_CACHE_SIZE
          value: "256MB"
  # Override volumeClaimTemplates for prod environment
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
