apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: skill-management-system-dev
resources:
- ../../base
- ingress.yaml
- namespace.yaml
namespace: skill-management-system-dev
namePrefix: dev-
configMapGenerator:
- behavior: merge
  literals:
  - KC_DB_URL=jdbc:postgresql://dev-sms-postgres-service:5433/keycloak
  - BACKEND_HOST=http://localhost:8080
  - FRONTEND_HOST=http://localhost:3000
  name: keycloak-config
- behavior: merge
  literals:
  - KC_SPI_EVENTS_LISTENER_WEBHOOK_EVENT_LISTENER_WEBHOOK_URL=http://host.docker.internal:8080/api/v1/webhooks/keycloak
  name: keycloak-webhook-config
replicas:
- count: 1
  name: postgres
- count: 1
  name: keycloak
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: dev
    environment: development
patches:
- path: postgres-patch.yaml
- path: keycloak-patch.yaml
