apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc
  labels:
    app: sonarqube
    component: server
    part-of: skill-management-devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
