apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  labels:
    app: sonarqube
    component: server
    part-of: skill-management-devops
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
  selector:
    app: sonarqube
